language: node_js
node_js:
  - "node"
cache: yarn

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $TOKEN
  local_dir: build
  on:
    branch: master
